Feature/disable link api
mohammadKarimi/SwiftLink pull request #83
Opened 2024-02-10 19:10 UTC by parhamdarvishi

Feature/disable link api

2024-02-10 19:33 UTC, mohammadKarimi requested changes

2024-02-10 19:33 UTC, mohammadKarimi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommandHandler.cs
> +        link.IsDisabled = true;
You cant set IsDisable to true directly, you have to add a behavior inside your domain to do it.
Because we want to move our domains from anemic to rich one.

2024-02-10 19:33 UTC, mohammadKarimi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommand.cs
> +namespace SwiftLink.Application.UseCases.Links.Commands.DisableLink;
Please remove end of namespace, until commands is enough.

2024-02-10 19:33 UTC, mohammadKarimi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommand.cs
> +public class DisableLinkCommand : IRequest<Result<bool>>
Please use record for immutability.

2024-02-10 19:33 UTC, mohammadKarimi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommandHandler.cs
> +        link.IsDisabled = true;
Make this property in your domain as private set;

2024-02-10 19:33 UTC, mohammadKarimi commented on src/SwiftLink.Presentation/Controllers/LinkController.cs
> +    public async Task<IActionResult> DisableLink([FromRoute] int id,
In order to have clear route, it is enough to have disable instead of disableLink

Don't forget DRY principle.


Better :
/link/disable

Bad:
/link/disableLink

2024-02-11 06:39 UTC, parhamdarvishi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommandHandler.cs
> +        link.IsDisabled = true;
very good point.

I read new article today for this point in medium [https://medium.com/@inzuael/anemic-domain-model-vs-rich-domain-model-78752b46098f](url) and I will use it in other parts of project.

2024-02-11 06:39 UTC, parhamdarvishi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommand.cs
> +namespace SwiftLink.Application.UseCases.Links.Commands.DisableLink;
sure.

2024-02-11 10:14 UTC, mohammadKarimi requested changes

2024-02-11 10:14 UTC, mohammadKarimi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommandHandler.cs
> +        link.DisableLink();
Again DRY Principle. 
please dont repeat yourself. link.Disable() is enough.

2024-02-11 10:14 UTC, mohammadKarimi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommand.cs
> +    public int Id { get; set; }
for one parameter it is better to use primary constructor. 

`public record DisableLinkCommand(int Id) : IRequest<Result<bool>>;`

2024-02-11 10:26 UTC, parhamdarvishi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommandHandler.cs
> +        link.DisableLink();
good point.

I must work on myself specifically on naming.

2024-02-11 10:26 UTC, parhamdarvishi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommand.cs
> +    public int Id { get; set; }
Sure.

I changed it.

2024-02-11 10:51 UTC, parhamdarvishi commented on src/SwiftLink.Presentation/Controllers/LinkController.cs
> +    public async Task<IActionResult> DisableLink([FromRoute] int id,
sure.

I changed it

2024-02-11 10:51 UTC, parhamdarvishi commented on src/SwiftLink.Application/UseCases/Links/Commands/DisableLink/DisableLinkCommandHandler.cs
> +        link.IsDisabled = true;
Prefect point.

I changed it.

2024-02-11 13:27 UTC, mohammadKarimi approved these changes
Perfect

2024-02-12 09:34 UTC, mohammadKarimi approved these changes

2024-02-12 09:41 UTC, merged